apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: masajid
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: masajid
        tier: frontend
    spec:
      containers:
      - image: us.gcr.io/masajid-252320/masajid-frontend:1.0.0
        name: nginx
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
