rvm:
  - 2.7.0

cache: bundler

services:
  - docker
  - postgresql

addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver

env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}

gemfile:
  - web_container/Gemfile
  - engines/admin/Gemfile
  - engines/content/Gemfile
  - engines/landing/Gemfile
  - engines/public/Gemfile

before_install:
  - cd $(dirname $BUNDLE_GEMFILE)

install:
  - if [ -d 'spec/dummy' ]; then cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml; fi
  - bundle install --jobs=3 --retry=3
  - if [ -d 'spec/dummy' ]; then bundle exec rails db:test:prepare; fi

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script:
  - bundle exec rubocop
  - if [ -d 'spec/dummy' ]; then bundle exec rspec ; fi
  - if [ -d 'spec/dummy' ]; then HEADLESS=true bundle exec rspec -t system ; fi

stages:
  - test
  - name: deploy
    if: branch = production

jobs:
  include:
    - stage: deploy
      before_install:
        - cd ${PWD}
      install:
        - openssl aes-256-cbc -K $encrypted_01c4308a40f4_key -iv $encrypted_01c4308a40f4_iv -in service-account.json.enc -out service-account.json -d
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file service-account.json
        - gcloud auth configure-docker
        - gcloud config set project ${GKE_PROJECT_ID}
        - gcloud config set compute/zone ${GKE_ZONE}
        - gcloud container clusters get-credentials ${GKE_CLUSTER}
      script: sh deploy.sh
