rvm:
  - 2.6.3

gemfile:
  - web_container/Gemfile

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec

before_install:
  - cd $(dirname $BUNDLE_GEMFILE)
