rvm:
  - 2.6.3

cache: bundler

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

gemfile:
  - web_container/Gemfile
  - engines/admin/Gemfile
  - engines/content/Gemfile
  - engines/landing/Gemfile
  - engines/public/Gemfile

before_install:
  - cd $(dirname $BUNDLE_GEMFILE)

script:
  - bundle exec rubocop

stages:
  - test
  - name: deploy
    if: branch = production

jobs:
  include:
    - stage: deploy
      before_script:
        - cd ${TRAVIS_BUILD_DIR}
        - openssl aes-256-cbc -K $encrypted_01c4308a40f4_key -iv $encrypted_01c4308a40f4_iv -in service-account.json.enc -out service-account.json -d
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file service-account.json
        - gcloud auth configure-docker
        - gcloud config set project ${GKE_PROJECT_ID}
        - gcloud config set compute/zone ${GKE_ZONE}
        - gcloud container clusters get-credentials ${GKE_CLUSTER}
      script: sh deploy.sh
