rvm:
  - 2.6.3

cache: bundler

services:
  - postgresql

gemfile:
  - web_container/Gemfile

script:
  - bundle exec rspec spec

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

before_install:
  - cp web_container/config/database.yml.travis $(dirname $BUNDLE_GEMFILE)/config/database.yml
  - cd $(dirname $BUNDLE_GEMFILE)
