rvm:
  - 2.6.3

cache: bundler

services:
  - postgresql

env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
  - bundle exec rspec spec

before_script:
  - cd web_container && RAILS_ENV=test bundle exec rake db:create db:migrate

deploy:
  provider: script
  script: sh deploy.sh
  on:
    branch: chore/travis_ci_test_deploy
