FROM ruby:2.7.0

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    postgresql-client \
    nodejs \
  && apt-get -q clean \
  && rm -rf /var/lib/apt/lists

WORKDIR /app/web_container

COPY web_container/Gemfile* ./
COPY engines ../engines
RUN bundle install
COPY web_container .

ARG RAILS_MASTER_KEY
ENV RAILS_MASTER_KEY ${RAILS_MASTER_KEY}
ENV RAILS_ENV production

RUN mkdir -p tmp/pids

RUN rails assets:precompile

CMD puma -C config/puma.rb
