version: '3'

services:
  db:
    image: postgres:11
    env_file: web_container/.env.prod
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    command: redis-server
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: web_container/.env.prod
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - storage:/app/web_container/storage
    depends_on:
      - db
      - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: web_container/.env.prod
    volumes:
      - storage:/app/web_container/storage
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=masajid.world
      - SUBDOMAINS=wildcard,
      - VALIDATION=http
      # - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      # - EMAIL=<e-mail> #optional
      # - DHLEVEL=2048 #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      # - STAGING=false #optional
    volumes:
      - ./nginx:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

volumes:
  redis:
  db-data:
  storage:
