version: '3'

services:
  db:
    image: postgres:11
    env_file: web_container/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0
    volumes:
      - redis:/data
    ports:
      - 6380:6379

  app: &app_base
    build: .
    env_file: web_container/.env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  sidekiq:
    <<: *app_base
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    depends_on:
      - app

volumes:
  redis:
  db-data:
