FROM ruby:2.6.3

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    postgresql-client \
    nodejs \
    vim \
  && apt-get -q clean \
  && rm -rf /var/lib/apt/lists

WORKDIR /app/web_container

COPY web_container/Gemfile* ./
COPY engines ../engines
RUN bundle install
COPY web_container .

ENV RAILS_ENV production

RUN rails assets:precompile

EXPOSE 3000
CMD rails server -b 0.0.0.0
