version: '3'

services:
  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - web_container/.env

  redis:
    image: redis:4.0-alpine
    command: redis-server --requirepass yourpassword
    volumes:
      - redis:/data

  app:
    env_file: web_container/.env
    build: .
    volumes:
    - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  sidekiq:
    env_file: web_container/.env
    build: .
    volumes:
      - .:/app
    command: sidekiq -C config/sidekiq.yml.erb
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  postgres:
