version: '3'

services:
  db:
    image: postgres:11
    env_file: web_container/.env.prod
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    command: redis-server
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: web_container/.env.prod
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: web_container/.env.prod
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

volumes:
  redis:
  db-data:
