kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: masajid
  POSTGRES_USER: masajid
  POSTGRES_PASSWORD: CPnmdlABCmSCl419
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: postgres-disk
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: masajid-frontend
  labels:
    app: masajid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masajid-frontend
  template:
    metadata:
      labels:
        app: masajid-frontend
    spec:
      containers:
      - name: masajid-frontend
        image: eu.gcr.io/masajid-252320/masajid:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          value: "7c7b183f59c356cc7277279711d0ace4"
        - name: PROJECT_HOSTNAME
          value: "localhost:3000"
        - name: POSTGRES_USER
          value: "masajid"
        - name: POSTGRES_PASSWORD
          value: "CPnmdlABCmSCl419"
        - name: POSTGRES_DATABASE
          value: "masajid"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: SUPER_ADMIN_EMAIL
          value: "admin@masajid.com"
        - name: SUPER_ADMIN_PASSWORD
          value: "masajid"
        - name: ADMIN_SENDER_EMAIL
          value: "admin@gmail.com"
        - name: ADMIN_NOTIFICATION_EMAILS
          value: "admin@gmail.com,admin_2@gmail.com"
        - name: MAILJET_API_KEY
          value: "091e123850da5deb5373b15d5cd7e549"
        - name: MAILJET_SECRET_KEY
          value: "9e3df088906f46a6c7069469caac43a2"
        - name: MAPBOX_ACCESS_TOKEN
          value: "pk.eyJ1IjoibWdoYXJiaWsiLCJhIjoiY2pyNWJncTdvMWhuNTQ0cmx3c2xta2hkaiJ9.JJz956L-n8pyAzYBoHDXhw"