inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - spec/dummy/**/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false
