source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'content', path: '../content'

# TODO: cleanup after rails 6.3 is supported
gem 'trix-gem', github: 'masajid/trix-gem', branch: 'chore/support_rails_6_3'
