source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'content', path: '../content'

# TODO: cleanup after nested attributes are supported
gem 'trix-rails', github: 'masajid/trix', branch: 'master'
