development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials[Rails.env.to_sym][:redis_url] || 'redis://localhost:6379/1' %>
  channel_prefix: masajid_production
