default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.postgres[:host] %>
  port: 5432
  username: <%= Rails.application.credentials.postgres[:user] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: masajid_development

test:
  <<: *default
  database: masajid_test

production:
  <<: *default
  database: <%= Rails.application.credentials.postgres[:db] %>
