source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'content', path: '../content'

instance_eval File.read('../content/lib/content/dependencies/test.rb')
