inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - spec/dummy/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/**

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
