source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.3'
gem 'rails', '~> 6.0.0'
gem 'sass-rails', '~> 5'

gem 'jbuilder', '~> 2.9'
gem 'turbolinks', '~> 5'

# gem 'redis', '~> 4.0'
# gem 'bcrypt', '~> 3.1.7'

gem 'bootsnap', '>= 1.4.2', require: false

gem 'flipper-ui', '~> 0.17.1'
gem 'jquery-rails'
gem 'whenever', require: false

group :production do
  gem 'google-cloud-storage', '~> 1.25', require: false
  gem 'mailjet'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails', '~> 2.7.5'
  gem 'rubocop-rails', '~> 2.4.2'
end

group :development do
  gem 'letter_opener_web'
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  # gem 'capybara', '>= 2.15'
  # gem 'webdrivers'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

path '../engines' do
  gem 'admin'
  gem 'content'
  gem 'landing'
  gem 'public'
end
