name: ci

on:
  push:
    branches:
      - feat/upgrade_rails_6_0_6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2 # TODO: upgrade to v3
        with:
          context: .
          file: ./Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  |
            ${{ secrets.DOCKER_HUB_USERNAME }}/masajid:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/masajid:${{ github.sha }}
          build-args: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/masajid:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/masajid:buildcache,mode=max
